=encoding utf8

=head1 La culture et les ressources Perl 6

=over 4

L<Aperitifs|"Aperitifs | Apetizers"> | L<Apetizers|"Aperitifs | Apetizers">

L<Presentation|"Presentation | Introduction"> | L<Introduction|"Presentation | Introduction">

=over 4

L<Le jeu de la boisson du CPAN |"Le jeu de la boisson du CPAN | The CPAN drinking game"> | L<The CPAN drinking game |"Le jeu de la boisson du CPAN | The CPAN drinking game">

=back

L<Idees directrices|"Idees directrices | Keynotes"> | L<Keynotes|"Idees directrices | Keynotes">

=over 4

L<L'etat de l'onion de 1997 a 1999|"L'etat de l'onion de 1997 a 1999 | The state of the onion from 1997 to 1999"> | L<The state of the onion from 1997 to 1999|"L'etat de l'onion de 1997 a 1999 | The state of the onion from 1997 to 1999">

L<L'etat de l'onion de 2000 a 2009|"L'etat de l'onion de 2000 a 2009 | The state of the onion from 2000 to 2009"> | L<The state of the onion from 2000 to 2009|"L'etat de l'onion de 2000 a 2009 | The state of the onion from 2000 to 2009"> 

=back

L<Les synopsis|"Les synopsis | Synopsis (Specification)"> (I<Specification>) | L<Synopsis|"Les synopsis | Synopsis (Specification)"> (I<Specification>)

=over 4

L<Les synopsis de 1 a 9|"Les synopsis de 1 a 9 | Synopsis from 1 to 9"> | L<Synopsis from 1 to 9|"Les synopsis de 1 a 9 | Synopsis from 1 to 9">

L<Les synopsis de 10 a 19|"Les synopsis de 10 a 19 | Synopsis from 10 to 19"> | L<Synopsis from 10 to 19|"Les synopsis de 10 a 19 | Synopsis from 10 to 19">

L<Les synopsis de 20 a 29|"Les synopsis de 20 a 29 | Synopsis from 20 to 29"> | L<Synopsis from 20 to 29|"Les synopsis de 20 a 29 | Synopsis from 20 to 29">

L<Les synopsis de 30 a 33|"Les synopsis de 30 a 33 | Synopsis from 30 to 33"> | L<Synopsis from 30 to 33|"Les synopsis de 30 a 33 | Synopsis from 30 to 33">

=back


L<Les Apocalypses|"Les Apocalypses (Justification) | Apocalypses (Justification)"> (I<Justification>) | L<Apocalypses|"Les Apocalypses (Justification) | Apocalypses (Justification)"> (I<Justification>)

=over 4

L<Les Apocalypses de 1 a 6|"Les Apocalypses de 1 a 6 | Apocalypses from 1 to 6"> | L<Apocalypses from 1 to 6 and, 12|"Les Apocalypses de 1 a 6 | Apocalypses from 1 to 6">

L<L'Apocalypses 12|"L'Apocalypse 12 | Apocalypse 12"> | L<Apocalypses 12|"L'Apocalypse 12 | Apocalypse 12">

L<L'Apocalypses 20|"L'Apocalypse 20 | Apocalypse 20"> | L<Apocalypses 20|"L'Apocalypse 20 | Apocalypse 20">

=back

L<Exegese|"Exegese (explication) | Exegesis (Explanation)"> (I<Explication>) | L<Exegesis|"Exegese (explication) | Exegesis (Explanation)"> (I<Explanation>)

=over 4

L<Exegese de 1 a 7|"Exegese de 1 a 7 | Exegesis from 1 to 7"> | L<Exegesis from 1 to 7|"Exegese de 1 a 7 | Exegesis from 1 to 7">

=back

L<Les comprimes|"Les Comprimes | Tablets"> | L<Tablets|"Les Comprimes | Tablets"> 

=over 4

L<Perl 6 Comprimes: introduction|"Perl 6 Comprimes: introduction | Perl 6 Tablets: Introduction"> | L<Perl 6 Tablets: Introduction|"Perl 6 Comprimes: introduction | Perl 6 Tablets: Introduction">

L<Les comprimes de 0 a 9|"Les comprimes de 0 a 9 | Tablets from 0 to 9"> | L<Tablets from 0 to 9|"Les comprimes de 0 a 9 | Tablets from 0 to 9">

L<Les comprimes 10|"Les comprimes 10 | Tablets 10"> | L<Tablets 10|"Les comprimes 10 | Tablets 10">

L<Annexe de 'a' a 'h'|"Annexe de 'a' a 'h' | Tablets from 'a' to 'h'"> | L<ablets from 'a' to 'h'|"Annexe de 'a' a 'h' | Tablets from 'a' to 'h'">

=back

=for L<Calendrier |"Le calendrier | Schedule"> | L<Schedule |"Le calendrier | Schedule">

=for =over 4

=for L<Calendrier entier|"Calendrier entier | Full schedule"> | L<Full schedule|"Calendrier entier | Full schedule">

=for L<Jour 1 |"Jour 1 | Day 1 20120629"> | L<Day 1|"Jour 1 | Day 1 20120629">

=for L<Jour 2 |"Jour 2 | Day 2 20120630"> | L<Day 2|"Jour 2 | Day 2 20120630">

=for =back

L<Lectures|"Lectures | Readings"> | L<Readings|"Lectures | Readings">

L<References|"References | References"> | L<References|"References | References">

=back

=head1 Aperitifs | Apetizers

Les talks de Larry Wall au tout début "L<State of the onion|http://www.perlfoundation.org/perl6/index.cgi?state_of_the_onion>" sont une bonne source d'information de base sur la culture et la façon de penser en Perl 6.

Larry Wall's yearly "L<State of the onion|http://www.perlfoundation.org/perl6/index.cgi?state_of_the_onion>" talks are a good source of background information on the thinking and culture behind Perl 6.

"I<... Now, you may be wondering what all this has to do with Perl. The fact is, 
your brains are built to do Perl programming. You have a deep desire to turn the 
complex into the simple, and Perl is just another tool to help you do that--just 
as I am using English right now to try to simplify reality. I can use English for 
that because English is a mess... >" 

=over 20

Larry Wall

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head1 Presentation | Introduction

=head2 Le jeu de la boisson du CPAN | The CPAN drinking game

Beaucoup de personnes aiment la bierre. Beaucoup de I<Perl Hackers> sont des gens. Alors quoi de mieux pour commencer cette ébauche (pas de jeux de mots voulu) que de décrire le jeu de la boisson du CPAN L<appuyez ici|https://github.com/perl6/mu/blob/master/docs/AES/S27draft.pod#___top> pour lire la suite en VO...

Many people love beer. Many I<Perl hackers> are people. Thus what better way to begin this draft (no pun intended) than to describe the CPAN Drinking Game L<click here|https://github.com/perl6/mu/blob/master/docs/AES/S27draft.pod#___top>...

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head1 Idees directrices | Keynotes

=head2 L'etat de l'onion de 1997 a 1999 | The state of the onion from 1997 to 1999

=over 4

L'état de l'onion 1 L<lire|http://www.wall.org/~larry/keynote/keynote.html>... (1997) 
| I<The state of the onion 1> L<read|http://www.wall.org/~larry/keynote/keynote.html>... (1997)

L'état de l'onion 2 L<lire|http://www.wall.org/~larry/onion/onion.html>... (1998) 
| I<The state of the onion 2> L<read|http://www.wall.org/~larry/onion/onion.html>... (1998)

L'état de l'onion 3 L<lire|http://www.wall.org/~larry/onion3/talk.html>... (1999)  
| I<The state of the onion 3> L<read|http://www.wall.org/~larry/onion3/talk.html>... (1999)

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head2 L'etat de l'onion de 2000 a 2009 | The state of the onion from 2000 to 2009

=over 4

L'état de l'onion 4 L<lire|http://www.perl.com/pub/a/2000/10/23/soto2000.html>... (2000) 
| I<The state of the onion 4> L<read|http://www.perl.com/pub/a/2000/10/23/soto2000.html>... (2000)

L'état de l'onion 5 L<lire|http://www.perl.com/pub/a/2001/07/25/onion.html>... (2001) 
| I<The state of the onion 5> L<read|http://www.perl.com/pub/a/2001/07/25/onion.html>... (2001)

L'état de l'onion 6 L<lire|http://dev.perl.org/perl6/talks/2002/onion2002/2002.txt.htm>... (2002) 
| I<The state of the onion 6> L<read|http://dev.perl.org/perl6/talks/2002/onion2002/2002.txt.htm>... (2002)

L'état de l'onion 7 L<lire|http://www.perl.com/pub/a/2003/07/16/soto2003.html?page=1>... (2003) 
| I<The state of the onion 7> L<read|http://www.perl.com/pub/a/2003/07/16/soto2003.html?page=1>... (2003)

L'état de l'onion 8 L<lire|http://www.perl.com/pub/a/2004/08/18/onion.html>... (2004) 
| I<The state of the onion 8> L<read|http://www.perl.com/pub/a/2004/08/18/onion.html>... (2004)

L'état de l'onion 9 L<lire|http://www.perl.com/pub/a/2005/09/22/onion.html>... (2005) 
| I<The state of the onion 9> L<read|http://www.perl.com/pub/a/2005/09/22/onion.html>... (2005)

L'état de l'onion 10 L<lire|http://www.perl.com/pub/a/2006/09/21/onion.html>... (2006) 
| I<The state of the onion 10> L<read|http://www.perl.com/pub/a/2006/09/21/onion.html>... (2006)

L'état de l'onion 11 L<lire|http://www.perl.com/pub/a/2007/12/06/soto-11.html>... (2007) 
| I<The state of the onion 11> L<read|http://www.perl.com/pub/a/2007/12/06/soto-11.html>... (2007)

L'état de l'onion 12 L<lire|http://www.perl.com/TBD>... (2008) 
| I<The state of the onion 12> L<read|http://www.perl.com/TBD>... (2008)

L'état de l'onion 13 L<lire|http://www.perl.com/TBD>... (2009) 
| I<The state of the onion 13> L<read|http://www.perl.com/TBD>... (2009)

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head1 Les synopsis | Synopsis (Specification)

=head2 Les synopsis de 1 a 9 | Synopsis from 1 to 9

=over 4

Synopsis 1 - vue d'ensemble L<lire|https://github.com/perl6/specs/blob/master/S01-overview.pod>...
| I<Synopsis 1 - Overview> L<read|https://github.com/perl6/specs/blob/master/S01-overview.pod>...

Synopsis 2 - Bits et Pièces L<lire|https://github.com/perl6/specs/blob/master/S02-bits.pod>...
| I<Synopsis 2 - Bits and Pieces> L<read|https://github.com/perl6/specs/blob/master/S02-bits.pod>...

Synopsis 3 - Opérateurs Perl 6 L<lire|https://github.com/perl6/specs/blob/master/S03-operators.pod>...
| I<Synopsis 3 - Perl 6 Operators> L<read|https://github.com/perl6/specs/blob/master/S03-operators.pod>...

Synopsis 4 - Blocks et déclarations L<lire|https://github.com/perl6/specs/blob/master/S04-control.pod>...
| I<Synopsis 4 - Blocks and Statements> L<read|https://github.com/perl6/specs/blob/master/S04-control.pod>...

Synopsis 5 - Les Regex et les Lois L<lire|https://github.com/perl6/specs/blob/master/S05-regex.pod>...
| I<Synopsis 5 - Regexes and Rules> L<read|https://github.com/perl6/specs/blob/master/S05-regex.pod>...

Synopsis 6 - Les sous-routines L<lire|https://github.com/perl6/specs/blob/master/S06-routines.pod>...
| I<Synopsis 6 - Subroutines> L<read|https://github.com/perl6/specs/blob/master/S06-routines.pod>...

Synopsis 7 - Itérateurs et Paresse L<lire|https://github.com/perl6/specs/blob/master/S07-iterators.pod>...
| I<Synopsis 7 - Iterators and Laziness> L<read|https://github.com/perl6/specs/blob/master/S07-iterators.pod>...

Synopsis 8 - Les types Parcel et Capture L<lire|https://github.com/perl6/specs/blob/master/S08-capture.pod>...
| I<Synopsis 8 - Capture and Parcel> L<read|https://github.com/perl6/specs/blob/master/S08-capture.pod>...

Synopsis 9 - Structures de données L<lire|https://github.com/perl6/specs/blob/master/S09-data.pod>...
| I<Synopsis 9 - Data Structures> L<read|https://github.com/perl6/specs/blob/master/S09-data.pod>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head2 Les synopsis de 10 a 19 | Synopsis from 10 to 19

=over 4

Synopsis 10 - Les paquetages L<lire|https://github.com/perl6/specs/blob/master/S10-packages.pod>...
| I<Synopsis 10 - Packages> L<read|https://github.com/perl6/specs/blob/master/S10-packages.pod>...

Synopsis 11 - Les modules L<lire|https://github.com/perl6/specs/blob/master/S11-modules.pod>...
| I<Synopsis 11 - Modules> L<read|https://github.com/perl6/specs/blob/master/S11-modules.pod>...

Synopsis 12 - Les objects L<lire|https://github.com/perl6/specs/blob/master/S12-objects.pod>...
| I<Synopsis 12 - Objects> L<read|https://github.com/perl6/specs/blob/master/S12-objects.pod>...

Synopsis 13 - Les surcharges L<lire|https://github.com/perl6/specs/blob/master/S13-overloading.pod>...
| I<Synopsis 13 - Overloading> L<read|https://github.com/perl6/specs/blob/master/S13-overloading.pod>...

Synopsis 14 - Roles et Types Parametric [EBAUCHE] L<lire|https://github.com/perl6/specs/blob/master/S14-roles-and-parametric-types.pod>...
| I<Synopsis 14 - Roles and Parametric Types [DRAFT]> L<read|https://github.com/perl6/specs/blob/master/S14-roles-and-parametric-types.pod>...

Synopsis 15 - Unicodes I<Doit être fait>
| I<Synopsis 15 - Unicode > I<TBD>

EBAUCHE: Synopsis 16 - IO / Name Services L<lire|https://github.com/perl6/specs/blob/master/S16-io.pod>...
| I<DRAFT: Synopsis 16 - IO / Name Services> L<read|https://github.com/perl6/specs/blob/master/S16-io.pod>...

EBAUCHE: Synopsis 17 - Les Process et Concurrence L<lire|https://github.com/perl6/specs/blob/master/S17-concurrency.pod>...
| I<DRAFT: Synopsis 17 - Processes and Concurrency> L<read|https://github.com/perl6/specs/blob/master/S17-concurrency.pod>...

Synopsis 18 - Compilation I<Doit être fait>
| I<Synopsis 18 - Compiling > I<TBD>

EBAUCHE: Synopsis 19 - L'interface de ligne de commande L<lire|https://github.com/perl6/specs/blob/master/S19-commandline.pod>...
| I<DRAFT: Synopsis 19 - Command Line Interface> L<read|https://github.com/perl6/specs/blob/master/S19-commandline.pod>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head2 Les synopsis de 20 a 29 | Synopsis from 20 to 29

=over 4

Synopsis 20 - Introspection Ebauche
| I<Synopsis 20 - Introspection Draft>

EBAUCHE: Synopsis 21 - Appel de code etranger L<lire|https://github.com/perl6/specs/blob/master/S21-calling-foreign-code.pod>...
| I<DRAFT: Synopsis 21 - Calling Foreign Code> L<read|https://github.com/perl6/specs/blob/master/S21-calling-foreign-code.pod>...

Synopsis 22 - Format de Package [EBAUCHE] L<lire|https://github.com/perl6/specs/blob/master/S22-package-format.pod>...
| I<Synopsis 22 - Package Format [DRAFT]> L<read|https://github.com/perl6/specs/blob/master/S22-package-format.pod>...

Synopsis 23 - Sécurité I<Doit être fait>
| I<Synopsis 23 - Security> I<TBD>

Synopsis 24 - Les Tests L<lire|https://github.com/perl6/specs/blob/master/S24-testing.pod>...
| I<Synopsis 24 - Testing> L<read|https://github.com/perl6/specs/blob/master/S24-testing.pod>...

Synopsis 25 - Perl portable I<Doit être fait>
| I<Synopsis 25 - Portable Perl> I<TBD>

Synopsis 26 - La documentation L<lire|https://github.com/perl6/specs/blob/master/S26-documentation.pod>...
| I<Synopsis 26 - Documentation> L<read|https://github.com/perl6/specs/blob/master/S26-documentation.pod>...

Synopsis 27 - Perl Culture I<Ebauche>
| I<Synopsis 27 - Perl Culture> I<Draft>

[EBAUCHE] Synopsis 28 - Special Names [EBAUCHE] L<lire|https://github.com/perl6/specs/blob/master/S28-special-names.pod> 
| I<[DRAFT] Synopsis 28 - Special Names [DRAFT]> L<read|https://github.com/perl6/specs/blob/master/S28-special-names.pod>...

Synopsis 29 - Les Fonctions Builtin L<lire|https://github.com/perl6/specs/blob/master/S29-functions.pod>... 
| I<Synopsis 29 - Builtin Functions> L<read|https://github.com/perl6/specs/blob/master/S29-functions.pod>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head2 Les synopsis de 30 a 33 | Synopsis from 30 to 33

=over 4

Synopsis 30 - Bibliothèque standard I<Doit être fait>
| I<Synopsis 30 - Standard Perl library> I<TBD>

[EBAUCHE] Synopsis 31 - Pragmatic Modules L<lire|https://github.com/perl6/specs/blob/master/S31-pragmatic-modules.pod>... 
| I<[DRAFT] Synopsis 31 - Pragmatic Modules> L<read|https://github.com/perl6/specs/blob/master/S31-pragmatic-modules.pod>...

Blibliothèque de réglage | Setting library

=over 4

EBAUCHE: Synopsis 32 - Bibliothèqe de réglage - L'essentiel L<lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Basics.pod>...
| I<DRAFT: Synopsis 32 - Setting Library - Basics> L<read|https://github.com/perl6/specs/blob/master/S32-setting-library/Basics.pod>...

EBAUCHE: Synopsis 32 - Bibliothèque de réglage - Remboursable L<lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Callable.pod>...
| I<DRAFT: Synopsis 32 - Setting Library - Callable> L<read|https://github.com/perl6/specs/blob/master/S32-setting-library/Callable.pod>...

EBAUCHE: Synopsis 32 - Bibliothèque de réglage - Conteneurs.pod L<lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Containers.pod>...
| I<DRAFT: Synopsis 32 - Setting Library - Containers.pod> L<read|https://github.com/perl6/specs/blob/master/S32-setting-library/Containers.pod>...

EBAUCHE: Synopsis 32 - Bibliothèque de réglage - Exceptions L<lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Exception.pod>...
| I<DRAFT: Synopsis 32 - Setting Library - Exceptions> L<read|https://github.com/perl6/specs/blob/master/S32-setting-library/Exception.pod>...

EBAUCHE: Synopsis 32 - Bibliothèque de réglage - ES L<lire|https://github.com/perl6/specs/blob/master/S32-setting-library/IO.pod>...
| I<DRAFT: Synopsis 32 - Setting Library - IO> L<read|https://github.com/perl6/specs/blob/master/S32-setting-library/IO.pod>...

EBAUCHE: Synopsis 32 - Bibliothèque de réglage - Numérique L<lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Numeric.pod>...
| I<DRAFT: Synopsis 32 - Setting Library - Numeric> L<read|https://github.com/perl6/specs/blob/master/S32-setting-library/Numeric.pod>...

EBAUCHE: Synopsis 32 - Bibliothèque de réglage - Les lois L<lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Rules.pod>...
| I<DRAFT: Synopsis 32 - Setting Library - Rules> L<read|https://github.com/perl6/specs/blob/master/S32-setting-library/Rules.pod>...

EBAUCHE: Synopsis 32 - Bibliothèque de réglage - Str L<lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Str.pod>...
| I<DRAFT: Synopsis 32 - Setting Library - Str> L<read|https://github.com/perl6/specs/blob/master/S32-setting-library/Str.pod>...

Synopsis 32 - Bibliothèque de réglage - Temporel L<lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Temporal.pod>...
| I<Synopsis 32 - Setting Library - Temporal> L<read|https://github.com/perl6/specs/blob/master/S32-setting-library/Temporal.pod>...

=back

Synopsis 33 - Messages diagnostique I<Doit être fait>
| I<Synopsis 33 - Diagnostic messages> I<TBD>
 
=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head1 Les Apocalypses (Justification) | Apocalypses (Justification)

=head2 Les Apocalypses de 1 a 6 | Apocalypses from 1 to 6

=over 4

Apocalyse 1 - Le Salle, le Mauvais, et le Bon L<lire|http://www.perl6.org/archive/doc/design/apo/A01.html>... 
| I<Apocalyse 1 - The Ugly, the Bad, and the Good> L<read|http://www.perl6.org/archive/doc/design/apo/A01.html>...

Apocalyse 2 - Bits et Pieces L<lire|http://www.perl6.org/archive/doc/design/apo/A02.html>... 
| I<Apocalyse 2 - Bits and Pieces> L<read|http://www.perl6.org/archive/doc/design/apo/A02.html>...

Apocalyse 3 - Opérateurs L<lire|http://www.perl6.org/archive/doc/design/apo/A03.html>... 
| I<Apocalyse 3 - Opérators> L<read|http://www.perl6.org/archive/doc/design/apo/A03.html>...

Apocalyse 4 - Syntaxe L<lire|http://www.perl6.org/archive/doc/design/apo/A04.html>... 
| I<Apocalyse 4 - Syntax> L<read|http://www.perl6.org/archive/doc/design/apo/A04.html>...

Apocalyse 5 - Le filtrage par motif L<lire|http://www.perl6.org/archive/doc/design/apo/A05.html>... 
| I<Apocalyse 5 - Pattern matching> L<read|http://www.perl6.org/archive/doc/design/apo/A05.html>...

Apocalyse 6 - Sous-programmes L<lire|http://www.perl6.org/archive/doc/design/apo/A06.html>... 
| I<Apocalyse 6 - Subroutines> L<read|http://www.perl6.org/archive/doc/design/apo/A06.html>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head2 L'Apocalypse 12 | Apocalypse 12

=over 4

Apocalyse 12 - Objets L<lire|http://www.perl6.org/archive/doc/design/apo/A12.html>... 
| I<Apocalyse 12 - Objects> L<read|http://www.perl6.org/archive/doc/design/apo/A12.html>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head2 L'Apocalypse 20 | Apocalypse 20

=over 4

Apocalyse 20 - Debogage L<lire|https://github.com/perl6/mu/blob/master/docs/AES/A20draft.pod>... 
| I<Apocalyse 20 - Debugging> L<read|https://github.com/perl6/mu/blob/master/docs/AES/A20draft.pod>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head1 Exegese (explication) | Exegesis (Explanation)

=head2 Exegese de 1 a 7 | Exegesis from 1 to 7

=over 4

Exegese 2 - Bits et Pieces L<lire|http://www.perl6.org/archive/doc/design/exe/E02.html>... 
| I<Exegesis 2 - Bits and Pieces> L<read|http://www.perl6.org/archive/doc/design/exe/E02.html>...

Exegese 3 - Operateurs L<lire|http://www.perl6.org/archive/doc/design/exe/E03.html>... 
| I<Exegesis 3 - Bits and Pieces> L<read|http://www.perl6.org/archive/doc/design/exe/E03.html>...

Exegese 4 - Syntaxe L<lire|http://www.perl6.org/archive/doc/design/exe/E04.html>... 
| I<Exegesis 4 - Syntax> L<read|http://www.perl6.org/archive/doc/design/exe/E04.html>...

Exegese 5 - Le filtrage par motif L<lire|http://www.perl6.org/archive/doc/design/exe/E05.html>... 
| I<Exegesis 5 - Pattern matching> L<read|http://www.perl6.org/archive/doc/design/exe/E05.html>...

Exegese 6 - Sous-programmes L<lire|http://www.perl6.org/archive/doc/design/exe/E06.html>... 
| I<Exegesis 6 - Subroutines> L<read|http://www.perl6.org/archive/doc/design/exe/E06.html>...

Exegese 7 - Formats L<lire|http://www.perl6.org/archive/doc/design/exe/E07.pod>... 
| I<Exegesis 7 - Formats> L<read|http://www.perl6.org/archive/doc/design/exe/E07.pod>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head1 Les Comprimes | Tablets

=head2 Perl 6 Comprimes: introduction | Perl 6 Tablets: Introduction

=over 4

Perl 6 Comprimes - Introduction L<lire|https://github.com/perl6/tablets/blob/master/docs/introduction.txt>... 
| I<Perl 6 Tablets - Introduction> L<read|https://github.com/perl6/tablets/blob/master/docs/introduction.txt>...

=back

=head2 Les comprimes de 0 a 9 | Tablets from 0 to 9

=over 4

Perl 6 Comprimé 0 - histoire L<lire|https://github.com/perl6/tablets/blob/master/docs/tablet-0-history.txt>... 
| I<Perl 6 Tablet 0 - history> L<read|https://github.com/perl6/tablets/blob/master/docs/tablet-0-history.txt>...

Perl 6 Comprimé 1 - concept de langage L<lire|https://github.com/perl6/tablets/blob/master/docs/tablet-1-language-design.txt>... 
| I<Perl 6 Tablet 1 - language design> L<read|https://github.com/perl6/tablets/blob/master/docs/tablet-1-language-design.txt>...

Perl 6 Comprimé 2 - Syntaxe de base L<lire|https://github.com/perl6/tablets/blob/master/docs/tablet-2-basic-syntax.txt>... 
| I<Perl 6 Tablet 2 - Basic Syntax> L<read|https://github.com/perl6/tablets/blob/master/docs/tablet-2-basic-syntax.txt>...

Perl 6 Comprimé 3 - Variables L<lire|https://github.com/perl6/tablets/blob/master/docs/tablet-3-variables.txt>... 
| I<Perl 6 Tablet 3 - Variables> L<read|https://github.com/perl6/tablets/blob/master/docs/tablet-3-variables.txt>...

Perl 6 Comprimé 4 - Operateurs L<lire|https://github.com/perl6/tablets/blob/master/docs/tablet-4-operators.txt>... 
| I<Perl 6 Tablet 4 - Operators> L<read|https://github.com/perl6/tablets/blob/master/docs/tablet-4-operators.txt>...

Perl 6 Comprimé 5 - ES L<lire|https://github.com/perl6/tablets/blob/master/docs/tablet-5-io.txt>... 
| I<Perl 6 Tablet 5 - IO> L<read|https://github.com/perl6/tablets/blob/master/docs/tablet-5-io.txt>...

Perl 6 Comprimé 6 - Blocs L<lire|https://github.com/perl6/tablets/blob/master/docs/tablet-6-blocks.txt>... 
| I<Perl 6 Tablet 6 - Blocks> L<read|https://github.com/perl6/tablets/blob/master/docs/tablet-6-blocks.txt>...

Perl 6 Comprimé 7 - Sous routines L<lire|https://github.com/perl6/tablets/blob/master/docs/tablet-7-subroutines.txt>... 
| I<Perl 6 Tablet 7 - Subroutines> L<read|https://github.com/perl6/tablets/blob/master/docs/tablet-7-subroutines.txt>...

Perl 6 Comprimé 8 - Objets L<lire|https://github.com/perl6/tablets/blob/master/docs/tablet-8-objects.txt>... 
| I<Perl 6 Tablet 8 - Objetcs> L<read|https://github.com/perl6/tablets/blob/master/docs/tablet-8-objects.txt>...

Perl 6 Comprimé 9 - Expressions régulières L<lire|https://github.com/perl6/tablets/blob/master/docs/tablet-9-regexes.txt>... 
| I<Perl 6 Tablet 9 - Regexes> L<read|https://github.com/perl6/tablets/blob/master/docs/tablet-9-regexes.txt>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head2 Les comprimes 10 | Tablets 10

=over 4

Perl 6 Comprimé 10 - Metaprogramming L<lire|https://github.com/perl6/tablets/blob/master/docs/tablet-10-metaprogramming.txt>... 
| I<Perl 6 Tablet 10 - Metaprogramming> L<read|https://github.com/perl6/tablets/blob/master/docs/tablet-10-metaprogramming.txt>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head2 Annexe de 'a' a 'h' | Tablets from 'a' to 'h'

=over 4

annexe a - Index L<lire|https://github.com/perl6/tablets/blob/master/docs/appendix-a-index.txt>... 
| I<appendix a - index> L<read|https://github.com/perl6/tablets/blob/master/docs/appendix-a-index.txt>...

annexe b - Groupé L<lire|https://github.com/perl6/tablets/blob/master/docs/appendix-b-grouped.txt>... 
| I<appendix b - grouped> L<read|https://github.com/perl6/tablets/blob/master/docs/appendix-b-grouped.txt>...

annexe c - livre de cuisine L<lire|https://github.com/perl6/tablets/blob/master/docs/appendix-c-cookbook.txt>... 
| I<appendix c - cookbook> L<read|https://github.com/perl6/tablets/blob/master/docs/appendix-c-cookbook.txt>...

annexe d - delta L<lire|https://github.com/perl6/tablets/blob/master/docs/appendix-d-delta.txt>... 
| I<appendix d - delta> L<read|https://github.com/perl6/tablets/blob/master/docs/appendix-d-delta.txt>...

annexe e - excitant L<lire|https://github.com/perl6/tablets/blob/master/docs/appendix-e-exciting.txt>... 
| I<appendix e - exciting> L<read|https://github.com/perl6/tablets/blob/master/docs/appendix-e-exciting.txt>...

annexe f - faq L<lire|https://github.com/perl6/tablets/blob/master/docs/appendix-f-faq.txt>... 
| I<appendix f - faq> L<read|https://github.com/perl6/tablets/blob/master/docs/appendix-f-faq.txt>...

annexe g - glossary L<lire|https://github.com/perl6/tablets/blob/master/docs/appendix-g-glossary.txt>... 
| I<appendix g - glossary> L<read|https://github.com/perl6/tablets/blob/master/docs/appendix-g-glossary.txt>...

annexe h - href L<lire|https://github.com/perl6/tablets/blob/master/docs/appendix-h-href.txt>... 
| I<appendix h - href> L<read|https://github.com/perl6/tablets/blob/master/docs/appendix-h-href.txt>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=for =head1 Le calendrier | Schedule

=for =head2 Calendrier entier | Full schedule

=for =over 4

=for L<Liste des talk|http://journeesperl.fr/fpw2012/talks> | L<List of talks|http://journeesperl.fr/fpw2012/talks>

=for L<surprise ?|http://journeesperl.fr/fpw2012/talk/4142> L<Matt S Trout (mst)|http://journeesperl.fr/fpw2012/user/1846> 45 minutes English 15h00

=for L<Parrot statistics|http://journeesperl.fr/fpw2012/talk/4128> L<François Perrad (fperrad)|http://journeesperl.fr/fpw2012/user/2391> éclair Français

=for =back

=for L<Haut|"La culture et les ressources Perl 6"> 
=for | L<Top|"La culture et les ressources Perl 6">

=for =head2 Jour 1 | Day 1 20120629

=for =head3 Matin | Morning

=for =head3 EPITECH 1

=for =over 4

=for L<Ouverture|http://journeesperl.fr/fpw2012/event/1085> | L<Opening|http://journeesperl.fr/fpw2012/event/1085> 45 minutes 9h00

=for L<Le développement de Perl 5|http://journeesperl.fr/fpw2012/talk/4057> L<Philippe Bruhat (BooK)|http://journeesperl.fr/fpw2012/user/1> 20 minutes Français 10h00

=for L<Les nouveautés de Perl 5.16|http://journeesperl.fr/fpw2012/talk/4123> L<Sébastien Aperghis-Tramoni (Maddingue)|http://journeesperl.fr/fpw2012/user/15> 20 minutes Français 10h25

=for L<Introduction aux expressions régulières de Perl 5 et PCRE 7|http://journeesperl.fr/fpw2012/talk/4124> L<Sébastien Aperghis-Tramoni (Maddingue)|http://journeesperl.fr/fpw2012/user/15> 45 minutes Français 11h00

=for =back

=for =head3 EPITECH 2

=for =over 4

=for L<intro à perl6|http://journeesperl.fr/fpw2012/talk/4050> L<marc chantreux (eiro)|http://journeesperl.fr/fpw2012/user/4950> 45 minutes Français 10h00

=for L<Meta-programming In Perl 6|http://journeesperl.fr/fpw2012/talk/4053> L<Jonathan Worthington (jnthn)|http://journeesperl.fr/fpw2012/user/1174> 45 minutes English 11h00

=for =back

=for L<Haut|"La culture et les ressources Perl 6"> 
=for | L<Top|"La culture et les ressources Perl 6">

=for =head3 Aprés-midi | Afternoon

=for =head3 EPITECH 1

=for =over 4

=for L<DBIx::DataModel vs DBIx::Class|http://journeesperl.fr/fpw2012/talk/4100> L<Laurent Dami (dami)|http://journeesperl.fr/fpw2012/user/199> 45 minutes Français 14h00

=for L<SQL::Abstract::FromQuery|http://journeesperl.fr/fpw2012/talk/4099> L<Laurent Dami (dami)|http://journeesperl.fr/fpw2012/user/199> 20 minutes Français 15h00

=for L<Moo - almost, but not quite, two thirds of Moose|http://journeesperl.fr/fpw2012/talk/4151> L<Matt S Trout (mst)|http://journeesperl.fr/fpw2012/user/1846> 45 minutes English 15h25

=for L<l'inventaire des ordinateurs, hyperviseurs et des équipements réseaux|http://journeesperl.fr/fpw2012/talk/4113> L<Gonéri Le Bouder|http://journeesperl.fr/fpw2012/user/7870> 45 minutes Français 17h00

=for L<Restaurant du vendredi soir : brasserie Kohler-Rehm|http://journeesperl.fr/fpw2012/event/1084> (239 min) 20h00

=for =back

=for =head3 EPITECH 2

=for =over 4

=for L<Macros in Rakudo|http://journeesperl.fr/fpw2012/talk/4052> L<Carl Mäsak (masak)|http://journeesperl.fr/fpw2012/user/630> 45 minutes English 14h00

=for L<Bailador -- A Perl 6 port of Dancer|http://journeesperl.fr/fpw2012/talk/4122> L<Tadeusz Sośnierz ( tadzik)|http://journeesperl.fr/fpw2012/user/7132> 20 minutes English 15h00

=for L<Ligne de commande avec classe en Perl|http://journeesperl.fr/fpw2012/talk/4129> L<Vincent Bachelier (geistteufel)|http://journeesperl.fr/fpw2012/user/7617> 20 minutes Français 15h25

=for L<les outils autour du cpan: partagez et deployez du code Perl|http://journeesperl.fr/fpw2012/talk/4143> L<marc chantreux (eiro)|http://journeesperl.fr/fpw2012/user/4950> 45 minutes Français 15h50

=for L<MARC::MIR, le PSGI de l'informatique documentaire|http://journeesperl.fr/fpw2012/talk/4144> L<marc chantreux (eiro)|http://journeesperl.fr/fpw2012/user/4950> 45 minutes Français 17h00

=for =back

=for L<Haut|"La culture et les ressources Perl 6"> 
=for | L<Top|"La culture et les ressources Perl 6">

=for =head2 Jour 2 | Day 2 20120630

=for =head3 Matin | Morning

=for =head3 EPITECH 1

=for =over 4

=for L<SPORE - La solution polyglotte pour accéder aux API REST|http://journeesperl.fr/fpw2012/talk/4115> L<Camille Maussang (cmaussan)|http://journeesperl.fr/fpw2012/user/5021> 20 minutes Français 9h00

=for L<Un webservice facile avec Dancer & Spore|http://journeesperl.fr/fpw2012/talk/4116> L<Camille Maussang (cmaussan)|http://journeesperl.fr/fpw2012/user/5021> 45 minutes Français 9h30

=for L<Retours d'experience sur une utilisation avancée du MetaCPAN|http://journeesperl.fr/fpw2012/talk/4083> L<Erwan Ben Souiden (Labynocle)|http://journeesperl.fr/fpw2012/user/8511> 20 minutes Français 10h30

=for L<Des outils et des hommes|http://journeesperl.fr/fpw2012/talk/4101> L<Nils Grunwald|http://journeesperl.fr/fpw2012/user/4145> 45 minutes Français 11h00

=for =back

=for =head3 EPITECH 2

=for =over 4

=for L<perl debugging|http://journeesperl.fr/fpw2012/talk/4141> L<marc chantreux (eiro)|http://journeesperl.fr/fpw2012/user/4950> 20 minutes 9h00

=for L<die hard perl|http://journeesperl.fr/fpw2012/talk/4051> L<marc chantreux (eiro)|http://journeesperl.fr/fpw2012/user/4950> 45 minutes Français 9h30

=for L<Étendre Net-SNMP en Perl|http://journeesperl.fr/fpw2012/talk/4125> L<Sébastien Aperghis-Tramoni (Maddingue)|http://journeesperl.fr/fpw2012/user/15> 20 minutes Français 10h30

=for L<TDD in deeply embedded with TAP|http://journeesperl.fr/fpw2012/talk/4038> L<François Perrad (fperrad)|http://journeesperl.fr/fpw2012/user/2391> 20 minutes Français 11h00

=for L<Les (organis|http://journeesperl.fr/fpw2012/talk/4103>|L<associ|http://journeesperl.fr/fpw2012/talk/4103>|L<fond)ations de Perl|http://journeesperl.fr/fpw2012/talk/4103> L<Philippe Bruhat (BooK)|http://journeesperl.fr/fpw2012/user/1> 20 minutes Français 11h25

=for =back

=for L<Haut|"La culture et les ressources Perl 6"> 
=for | L<Top|"La culture et les ressources Perl 6">

=for =head3 Aprés-midi | Afternoon

=for =head3 EPITECH 1

=for =over 4

=for L<Big Data en perl|http://journeesperl.fr/fpw2012/talk/4145> L<iDavid Morel (dm)|http://journeesperl.fr/fpw2012/user/188> 45 minutes Français 14h00

=for L<Postmodern deconstructionism|http://journeesperl.fr/fpw2012/talk/4154> L<Matt S Trout (mst)|http://journeesperl.fr/fpw2012/user/1846> 45 minutes English 16h00

=for L<cloture|http://journeesperl.fr/fpw2012/event/1086> 45 minutes 17h15

=for =back

=for =head3 EPITECH 2

=for =over 4

=for L<De RackTables à rack, grâce au CPAN|http://journeesperl.fr/fpw2012/talk/4126> L<Sébastien Aperghis-Tramoni (Maddingue)|http://journeesperl.fr/fpw2012/user/15> 20 minutes Français 14h00

=for L<latex -O fun|http://journeesperl.fr/fpw2012/talk/4133> L<Jean Forget|http://journeesperl.fr/fpw2012/user/29> 20 minutes Français 14h25

=for =back

=for L<Haut|"La culture et les ressources Perl 6"> 
=for | L<Top|"La culture et les ressources Perl 6">

=head2 Lectures | Readings

=over 4

Utiliser Perl 6 - Un livre sur Perl 6 en développement L<lire|https://github.com/perl6/book>... | Using Perl 6 - a Perl 6 book in development L<read|https://github.com/perl6/book>...

Un livre à propos de NQP L<lire|https://github.com/perl6/nqpbook>... | A book about NQP L<read|https://github.com/perl6/nqpbook>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head1 References | References

=over 4

=item  L<Documentation officielle de Perl 6|http://perlcabal.org/syn/> | L<Official Perl 6 documentation|http://perlcabal.org/syn/>.

=item L<L'état de l'onion|http://www.perlfoundation.org/perl6/index.cgi?state_of_the_onion> | L<The onion state|http://www.perlfoundation.org/perl6/index.cgi?state_of_the_onion>.

=item L<Perl 6 RFC|http://www.perl6.org/archive/rfc/> | L<Perl 6 RFC|http://www.perl6.org/archive/rfc/>

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">
