=encoding utf8

=head1 La culture et les ressources Perl 6

=head1 Index

=over 4

L<Introduction|"Introduction">

Synopsis

=over 4

L<Synopsis 1-9|"Synopsis 1-9">

L<Synopsis 10-19|"Synopsis 10-19">

L<Synopsis 20-29|"Synopsis 20-29">

L<Synopsis 30-32|"Synopsis 30-32">

=back

L<La documentation|"La documentation">

=back

=head1 Introduction

Les talks de Larry Wall au tout début "L<State of the onion|http://www.perlfoundation.org/perl6/index.cgi?state_of_the_onion>" sont une bonne source d'information sur la culture et la façon de penser en Perl 6.

"I<... Now, you may be wondering what all this has to do with Perl. The fact is, 
your brains are built to do Perl programming. You have a deep desire to turn the 
complex into the simple, and Perl is just another tool to help you do that--just 
as I am using English right now to try to simplify reality. I can use English for 
that because English is a mess... >" 

=over 20

Larry Wall

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">



=head1 Synopsis 1-9

=over 4

Synopsis 1: vue d'ensemble | I<Synopsis 1: Overview>
L<Lire|https://github.com/perl6/specs/blob/master/S01-overview.pod>
| L<Read...|https://github.com/perl6/specs/blob/master/S01-overview.pod>...

Synopsis 2: Bits et Pieces | I<Synopsis 2: Bits and Pieces>
L<Lire|https://github.com/perl6/specs/blob/master/S02-bits.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S02-bits.pod>...

Synopsis 3: Operateurs Perl 6 | I<Synopsis 3: Perl 6 Operators>
L<Lire|https://github.com/perl6/specs/blob/master/S03-operators.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S03-operators.pod>...

Synopsis 4: Blocks et declarations | I<Synopsis 4: Blocks and Statements> 
L<Lire|https://github.com/perl6/specs/blob/master/S04-control.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S04-control.pod>...

Synopsis 5: Les Regex et les Lois | I<Synopsis 5: Regexes and Rules>
L<Lire|https://github.com/perl6/specs/blob/master/S05-regex.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S05-regex.pod>...

Synopsis 6: Les sous-routines | I<Synopsis 6: Subroutines>
L<Lire|https://github.com/perl6/specs/blob/master/S06-routines.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S06-routines.pod>...

Synopsis 7: Iterateurs et Paresse | I<Synopsis 7: Iterators and Laziness>
L<Lire|https://github.com/perl6/specs/blob/master/S07-iterators.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S07-iterators.pod>...

Synopsis 8: Les types Parcel, Capture | I<Synopsis 8: Capture and Parcel>
L<Lire|https://github.com/perl6/specs/blob/master/S08-capture.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S08-capture.pod>...

Synopsis 9: Structures de donnees | I<Synopsis 9: Data Structures>
L<Lire|https://github.com/perl6/specs/blob/master/S09-data.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S09-data.pod>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head1 Synopsis 10-19

=over 4

Synopsis 10: Les paquetages | I<Synopsis 10: Packages>
L<Lire|https://github.com/perl6/specs/blob/master/S10-packages.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S10-packages.pod>...

Synopsis 11: Les modules | I<Synopsis 11: Modules>
L<Lire|https://github.com/perl6/specs/blob/master/S11-modules.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S11-modules.pod>...

Synopsis 12: Les objects | I<Synopsis 12: Objects>
L<Lire|https://github.com/perl6/specs/blob/master/S12-objects.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S12-objects.pod>...

Synopsis 13: Les surcharges | I<Synopsis 13: Overloading>
L<Lire|https://github.com/perl6/specs/blob/master/S13-overloading.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S13-overloading.pod>...

Synopsis 14: Roles et Types Parametric [brouillon] | I<Synopsis 14: Roles and Parametric Types [DRAFT]>
L<Lire|https://github.com/perl6/specs/blob/master/S14-roles-and-parametric-types.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S14-roles-and-parametric-types.pod>...

BROUILLON: Synopsis 16: IO / Name Services | I<DRAFT: Synopsis 16: IO / Name Services>
L<Lire|https://github.com/perl6/specs/blob/master/S16-io.pod> 
| L<Read|https://github.com/perl6/specs/blob/master/S16-io.pod>...

DRAFT: Synopsis 17: Les Process et la Concurrence | I<DRAFT: Synopsis 17: Processes and Concurrency>
L<Lire|https://github.com/perl6/specs/blob/master/S17-concurrency.pod> 
| L<Read|https://github.com/perl6/specs/blob/master/S17-concurrency.pod>...

DRAFT: Synopsis 19: L'interface de ligne de commande | I<DRAFT: Synopsis 19: Command Line Interface>
L<Lire|https://github.com/perl6/specs/blob/master/S19-commandline.pod> 
| L<Read|https://github.com/perl6/specs/blob/master/S19-commandline.pod>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head1 Synopsis 20-29

=over 4

DRAFT: Synopsis 21: Appel de code etranger | I<DRAFT: Synopsis 21: Calling Foreign Code>
L<Lire|https://github.com/perl6/specs/blob/master/S21-calling-foreign-code.pod> 
| L<Read|https://github.com/perl6/specs/blob/master/S21-calling-foreign-code.pod>...

Synopsis 22: Format de Package [DRAFT] | I<Synopsis 22: Package Format [DRAFT]>
L<Lire|https://github.com/perl6/specs/blob/master/S22-package-format.pod> 
| L<Read|https://github.com/perl6/specs/blob/master/S22-package-format.pod>...

Synopsis 24: Les Tests | I<Synopsis 24: Testing>
L<Lire|https://github.com/perl6/specs/blob/master/S24-testing.pod> 
| L<Read|https://github.com/perl6/specs/blob/master/S24-testing.pod>...

Synopsis 26: La documentation | I<Synopsis 26: Documentation>
L<Lire|https://github.com/perl6/specs/blob/master/S26-documentation.pod> 
| L<Read|https://github.com/perl6/specs/blob/master/S26-documentation.pod>...

[BROUILLON] Synopsis 28 - Special Names [BROUILLON] | I<[DRAFT] Synopsis 28 - Special Names [DRAFT]>
L<Lire|https://github.com/perl6/specs/blob/master/S28-special-names.pod> 
| L<Read|https://github.com/perl6/specs/blob/master/S28-special-names.pod>...

Synopsis 29: Les Fonctions Builtin| I<Synopsis 29: Builtin Functions>
L<Lire|https://github.com/perl6/specs/blob/master/S29-functions.pod> 
| L<Read|https://github.com/perl6/specs/blob/master/S29-functions.pod>...

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head1 Synopsis 30-32

=over 4

[BROUILLON] Synopsis 31: Pragmatic Modules | I<[DRAFT] Synopsis 31: Pragmatic Modules>
L<Lire|https://github.com/perl6/specs/blob/master/S31-pragmatic-modules.pod> 
| L<Read|https://github.com/perl6/specs/blob/master/S31-pragmatic-modules.pod>...

Blibliothèque de réglage | Setting library

=over 4

BROUILLON: Synopsis 32: Bibliothèqe de réglage - L'essentiel | I<DRAFT: Synopsis 32: Setting Library - Basics>
L<Lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Basics.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S32-setting-library/Basics.pod>...

BROUILLON: Synopsis 32: Bibliothèque de réglage - Remboursable | I<DRAFT: Synopsis 32: Setting Library - Callable>
L<Lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Callable.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S32-setting-library/Callable.pod>...

BROUILLON: Synopsis 32: Bibliothèque de réglage - Conteneurs.pod | I<DRAFT: Synopsis 32: Setting Library - Containers.pod>
L<Lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Containers.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S32-setting-library/Containers.pod>...

BROUILLON: Synopsis 32: Bibliothèque de réglage - Exceptions | I<DRAFT: Synopsis 32: Setting Library - Exceptions>
L<Lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Exception.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S32-setting-library/Exception.pod>...

BROUILLON: Synopsis 32: Bibliothèque de réglage - ES | I<DRAFT: Synopsis 32: Setting Library - IO>
L<Lire|https://github.com/perl6/specs/blob/master/S32-setting-library/IO.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S32-setting-library/IO.pod>...

BROUILLON: Synopsis 32: Bibliothèque de réglage - Numérique | I<DRAFT: Synopsis 32: Setting Library - Numeric>
L<Lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Numeric.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S32-setting-library/Numeric.pod>...

BROUILLON: Synopsis 32: Bibliothèque de réglage - Les lois | I<DRAFT: Synopsis 32: Setting Library - Rules>
L<Lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Rules.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S32-setting-library/Rules.pod>...

BROUILLON: Synopsis 32: Bibliothèque de réglage - Str | I<DRAFT: Synopsis 32: Setting Library - Str>
L<Lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Str.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S32-setting-library/Str.pod>...

Synopsis 32: Bibliothèque de réglage - Temporel | I<Synopsis 32: Setting Library - Temporal>
L<Lire|https://github.com/perl6/specs/blob/master/S32-setting-library/Temporal.pod>
| L<Read|https://github.com/perl6/specs/blob/master/S32-setting-library/Temporal.pod>...

=back

=back

L<Haut|"La culture et les ressources Perl 6"> 
| L<Top|"La culture et les ressources Perl 6">

=head1 La documentation



=head1 Références

=over 4

L'état de l'onion: L<http://www.perlfoundation.org/perl6/index.cgi?state_of_the_onion>.

=back

